version: '3'

services:
  todolist-api2:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://db:3306/todolist_api?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: 123456
    restart: always
    depends_on:
      db:
          condition: service_healthy
  db:
    image: mysql:8.3.0 
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'todolist_api'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10